[server]
host = "0.0.0.0"
port = 5000
fileSize = 2147483648
enableH2C = false

[rateLimit]
requestLimit = 500
periodHours = 3.0

[security]
whiteList = []
blackList = []

[access]
whiteList = []
blackList = []
proxy = ""

[download]
maxImages = 10

[registries]
  [registries."ghcr.io"]
  upstream = "ghcr.io"
  authHost = "ghcr.io/token"
  authType = "github"
  enabled = true

  [registries."gcr.io"]
  upstream = "gcr.io"
  authHost = "gcr.io/v2/token"
  authType = "google"
  enabled = true

  [registries."quay.io"]
  upstream = "quay.io"
  authHost = "quay.io/v2/auth"
  authType = "quay"
  enabled = true

  [registries."registry.k8s.io"]
  upstream = "registry.k8s.io"
  authHost = "registry.k8s.io"
  authType = "anonymous"
  enabled = true

[tokenCache]
enabled = true
defaultTTL = "20m"